services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:mysecret@db:5432/postgres
    volumes:
      - ./backend:/app

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
